@(
    '[6th grade] Number 1 in school'
    '[Highschool] Fin Swimming Champion 3 years running'
    '[Highschool] basketball game'
    '[Highschool] LoL match comeback from 38-4 defecit with mundo'
    '[Highschool] 3rd year grade'
    '[Highschool] Joining Communication Engineering'
    '[College] Rising Up from 1st year failure'
    '[College] Being one of the strongest at Alaa Gym'
    '[College] Barely passing Digital Signal Processing'
    '[College] Graduation'
    '[Vodafone UK] Number 1 in First Call Resolution on training queue'
    '[Teleperformance] Suriving Complete Mental Breakdown'
    '[Not Courses] Achieving Level 16 English level (Maximum) on test'
    '[Not Courses] Landing First IT Job after 18 months of struggle'
    '[Centro] Device Clear Script'
    '[Centro] Userprofile Script'
    '[Centro] Powershell Toolkit'
    '[Centro] Senior IT Support'
    '[Centro] Psychological Healing with Dr. Mervat'
    '[Centro] Buying my first desk'
    '[Centro] Getting recruited by Intelligence Agency'
    '[Centro] Throwing away the System Admin Vacandy and going for the OSCP'
    '[Centro] Rescuing someone from Athiesm and reinforcing islamic faith'
    '[Centro] Major relationship experience'
    '[Centro] Owning the OSCP Lab network in 24 days under horrible conditions'
    '[Centro] Landing first Cybersecurity Job at Roaya'
    '[Roaya] Gaining some of Moms approval'
    '[Roaya] Landing my first real-world hack (112 compromised mailboxes)'
    '[Roaya] Handling PaloAlto like a boss in a short time'
    '[Roaya] Exchange Zero-Day Incident Response'
    '[Roaya] Header Script'
    '[Roaya] PowerEye Script collection'
    '[Roaya] First vision from God'
    '[Roaya] Learning to handle toxic thoughts better'
    '[Roaya] Landing my own apartment mortgage'
) | ForEach-Object {
    Write-Host -ForegroundColor Green "[+] $_"
}