@(
    '[6th grade] Number 1 in school'
    '[Highschool] Fin Swimming Champion 3 years running'
    '[Highschool] Record break in Fin Swimming Championship (19 seconds underwater 50m sprint)'
    '[Highschool] Basketball game (doing the MJ fadeaway)'
    '[Highschool] LoL match comeback from 38-4 defecit with mundo'
    '[Highschool] 3rd year grade'
    '[Highschool] Joining Communication Engineering'
    '[College] Rising Up from 1st year failure'
    '[College] Being one of the strongest at Alaa Gym'
    '[College] Barely passing Digital Signal Processing'
    '[College] Discovering Paleo diet'
    '[College] Graduation'
    '[Vodafone UK] Number 1 in First Call Resolution on training queue'
    '[Teleperformance] Suriving Complete Mental Breakdown'
    '[NotCourses] Achieving Level 16 English level (Maximum) on test'
    '[NotCourses] Landing First IT Job after 18 months of struggle'
    '[Centro] Junk Device Script'
    '[Centro] User Profile Script'
    '[Centro] PowerShell Toolkit'
    '[Centro] Senior IT Support'
    '[Centro] Psychological Healing with Dr. Mervat'
    '[Centro] Qutting gaming and starting my career in Cyber Security'
    '[Centro] Buying my first desk'
    '[Centro] Getting recruited by Intelligence Agency'
    '[Centro] Throwing away the System Admin Vacancy and going for the OSCP'
    '[Centro] Rescuing someone from Athiesm and reinforcing my Islamic faith'
    '[Centro] Major relationship experience'
    '[Centro] Learning more about mature masculinity'
    '[Centro] Owning the OSCP Lab network in 24 days under horrible conditions'
    '[Centro] Dropping a job with intelligence agency'
    '[Centro] Landing first Cybersecurity Job at Roaya'
    '[Roaya] Landing my first real-world hack (112 compromised mailboxes)'
    '[Roaya] Exchange Zero-Day Incident Response'
    '[Roaya] Header Script'
    '[Roaya] PowerEye'
    '[Roaya] Learning to handle toxic thoughts better'
) | ForEach-Object {
    Write-Host -ForegroundColor Green "[+] $_"
}